# Tarefa 03

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os Tutores
- Divirta-se :)

In [2]:
import pandas as pd
import requests

####  1) Lendo de APIs
Vimos em aula como carregar dados públicos do governo através de um API (*Application Programming Interface*). No exemplo de aula, baixamos os dados de pedidos de verificação de limites (PVL) realizados por estados, e selecionamos apenas aqueles referentes ao estado de São Paulo.

1. Repita os mesmos passos feitos em aula, mas selecione os PVLs realizados por municípios no estado do Rio de Janeiro.
2. Quais são os três *status* das solicitações mais frequentes na base? Quais são suas frequências?
3. Construa uma nova variável que contenha o ano do **status**. Observe que ```data_status``` vem como tipo *object* no **DataFrame**. Dica: você pode usar o método ```.str``` para transformar o tipo da variável em string, em seguida um método como [**slice()**](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.slice.html) ou [**split()**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.split.html).
4. Indique a frequência de cada ano do campo construído no item (3).

In [23]:
# 1) Repita os mesmos passos feitos em aula, mas selecione os PVLs realizados por municípios no estado do Rio de Janeiro.
url = 'http://apidatalake.tesouro.gov.br/ords/sadipem/tt/pvl?uf=RJ&tipo_interessado=Estado'
r = requests.get(url)
r.status_code
data_json = r.json()
# print(data_json['items'])
df = pd.DataFrame(data_json['items'])
df.head()

,id_pleito,tipo_interessado,interessado,cod_ibge,uf,num_pvl,status,num_processo,data_protocolo,tipo_operacao,finalidade,tipo_credor,credor,moeda,valor,pvl_assoc_divida,pvl_contradado_credor,data_status
0,7057,Estado,Rio de Janeiro,33,RJ,None,Encaminhado à PGFN com manifestação técnica fa...,17944.000487/2014-87,2014-04-24T00:00:00Z,Operação contratual interna (com garantia da U...,Infraestrutura,Instituição Financeira Nacional,Banco Nacional de Desenvolvimento Econômico e ...,Real,3.000000e+09,1,0,04/07/2014
1,7084,Estado,Rio de Janeiro,33,RJ,None,Encaminhado à PGFN com manifestação técnica fa...,17944.000493/2010-19,2010-08-06T00:00:00Z,Operação contratual externa (com garantia da U...,Fortalecimento Institucional,Instituição Financeira Internacional,Banco Internacional para Reconstrução e Desenv...,Dólar dos EUA,1.867300e+07,1,0,19/08/2010
2,8528,Estado,Rio de Janeiro,33,RJ,None,Deferido,17944.000793/2009-56,2009-07-17T00:00:00Z,Operação contratual interna,"Aquisição de terrenos, imóveis e/ou construção...",Instituição Financeira Nacional,Banco Nacional de Desenvolvimento Econômico e ...,Real,1.570000e+08,1,0,24/07/2009
3,9898,Estado,Rio de Janeiro,33,RJ,None,Deferido,17944.001076/2010-85,2011-05-25T00:00:00Z,Operação contratual interna,Saúde,Instituição Financeira Nacional,Banco do Brasil S/A,Real,1.328000e+08,0,0,07/06/2011
4,5645,Estado,Rio de Janeiro,33,RJ,None,Encaminhado à PGFN com manifestação técnica fa...,17944.000161/2013-79,2013-04-08T00:00:00Z,Operação contratual interna (com garantia da U...,Infraestrutura,Instituição Financeira Nacional,Banco Nacional de Desenvolvimento Econômico e ...,Real,3.031405e+09,1,0,06/05/2013

In [12]:
# 2) Quais são os três status das solicitações mais frequentes na base? Quais são suas frequências?
df['status'].value_counts() # Encaminhado à PGFN com manifestação técnica favorável (34), Deferido (14), Arquivado a pedido (3)

status
Encaminhado à PGFN com manifestação técnica favorável    34
Deferido                                                 14
Arquivado a pedido                                        3
Arquivado por decurso de prazo                            1
Name: count, dtype: int64

In [24]:
# 3) Construa uma nova variável que contenha o ano do status. 
# Observe que data_status vem como tipo object no DataFrame. 
# Dica: você pode usar o método .str para transformar o tipo da variável em string,
# em seguida um método como slice() ou split().
s = df['data_status']

# Converter para datetime
datas = pd.to_datetime(s, format="%d/%m/%Y")

# Extrair o ano
anos_dt = datas.dt.year
print(anos_dt)

# Usando .str.slice para pegar os 4 últimos caracteres
anos_str = s.str.slice(-4)
print(anos_str)

0     2014
1     2010
2     2009
3     2011
4     2013
5     2012
6     2011
7     2009
8     2013
9     2013
10    2013
11    2013
12    2002
13    2010
14    2012
15    2014
16    2014
17    2009
18    2011
19    2011
20    2011
21    2006
22    2012
23    2016
24    2009
25    2002
26    2012
27    2012
28    2012
29    2012
30    2014
31    2013
32    2009
33    2013
34    2012
35    2009
36    2002
37    2016
38    2006
39    2008
40    2002
41    2009
42    2012
43    2012
44    2016
45    2008
46    2009
47    2016
48    2011
49    2009
50    2012
51    2010
Name: data_status, dtype: int32
0     2014
1     2010
2     2009
3     2011
4     2013
5     2012
6     2011
7     2009
8     2013
9     2013
10    2013
11    2013
12    2002
13    2010
14    2012
15    2014
16    2014
17    2009
18    2011
19    2011
20    2011
21    2006
22    2012
23    2016
24    2009
25    2002
26    2012
27    2012
28    2012
29    2012
30    2014
31    2013
32    2009
33    2013
34    2012
35    2009
36    2002
37    2016
38    2006
39    2008
40    2002
41    2009
42    2012
43    2012
44    2016
45    2008
46    2009
47    2016
48    2011
49    2009
50    2012
51    2010
Name: data_status, dtype: object

####  2) Melhorando a interação com o API
Observe dois URLs de consultas diferentes, por exemplo o URL utilizado em aula, e o URL feito no exercício anterior. Compare-os e observe as diferenças.

1. Faça uma função em Python que recebe como argumento o UF da consulta e o tipo de interessado (```'Estado'```ou ```Município```), e que devolve os dados da consulta no formato *DataFrame*.
2. Quantas solicitações para o Estado podem ser consultadas para Minas Gerais com *status* em 'Arquivado por decurso de prazo' estão registradas?
3. Qual é o município da Bahia com mais solicitações deferidas?
4. Salve um arquivo .csv com os dados de solicitações da Bahia, com interessado = 'Estado'

In [26]:
#1) Faça uma função em Python que recebe como argumento o UF da consulta e o tipo de interessado ('Estado'ou Município),
# e que devolve os dados da consulta no formato DataFrame.
def getPVLsFromAPI(uf="RJ", tipo_interessado="Estado"):
    url = "http://apidatalake.tesouro.gov.br/ords/sadipem/tt/pvl?uf="+uf+"&tipo_interessado="+tipo_interessado
    r = requests.get(url)
    data_json = r.json()
    df = pd.DataFrame(data_json['items'])
    return df
getPVLsFromAPI(uf="SP")

,id_pleito,tipo_interessado,interessado,cod_ibge,uf,num_pvl,status,num_processo,data_protocolo,tipo_operacao,finalidade,tipo_credor,credor,moeda,valor,pvl_assoc_divida,pvl_contradado_credor,data_status
0,12416,Estado,São Paulo,35,SP,None,Encaminhado à PGFN com manifestação técnica fa...,17944.001682/2007-03,2007-12-13T00:00:00Z,Operação contratual externa (com garantia da U...,"Aquisição de máquinas, equipamentos e veículos",Instituição Financeira Internacional,Sumitomo Mitsui Banking Corporation,Dólar dos EUA,5.350000e+08,1,0,13/05/2008
1,9180,Estado,São Paulo,35,SP,None,Deferido,17944.000920/2008-36,2008-09-10T00:00:00Z,Operação contratual interna,PMAE,Instituição Financeira Nacional,Banco Nacional de Desenvolvimento Econômico e ...,Real,1.500000e+07,1,0,19/09/2008
2,9257,Estado,São Paulo,35,SP,None,Deferido,17944.000939/2009-63,2009-10-21T00:00:00Z,Operação contratual interna,"Aquisição de terrenos, imóveis e/ou construção...",Instituição Financeira Nacional,Banco Nacional de Desenvolvimento Econômico e ...,Real,2.400000e+08,1,0,12/11/2009
3,5003,Estado,São Paulo,35,SP,None,Deferido,17944.000022/2004-54,2004-06-01T00:00:00Z,Operação contratual interna,Educação,Instituição Financeira Nacional,Banco do Estado de São Paulo S/A,Real,2.982000e+07,1,0,04/06/2004
4,6543,Estado,São Paulo,35,SP,None,Encaminhado à PGFN com manifestação técnica fa...,17944.000376/2014-71,2014-08-04T00:00:00Z,Operação contratual externa (com garantia da U...,Infraestrutura,Instituição Financeira Nacional,Banco Santander (Brasil) S.A.,Dólar dos EUA,3.000000e+08,1,0,21/08/2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,7476,Estado,São Paulo,35,SP,None,Deferido,17944.000588/2014-58,2014-04-16T00:00:00Z,Operação contratual interna,Infraestrutura,Instituição Financeira Nacional,Banco Nacional de Desenvolvimento Econômico e ...,Real,1.700000e+09,1,0,30/04/2014
99,9123,Estado,São Paulo,35,SP,None,Encaminhado à PGFN com manifestação técnica fa...,17944.000908/2005-89,2005-07-28T00:00:00Z,Operação contratual externa (com garantia da U...,Preservação e recuperação ambiental,Instituição Financeira Internacional,Banco Interamericano de Desenvolvimento,Dólar dos EUA,9.000000e+06,1,0,25/01/2006
100,10836,Estado,São Paulo,35,SP,None,Encaminhado à PGFN com manifestação técnica fa...,17944.001297/2014-87,2015-11-13T15:12:11Z,Operação contratual interna (com garantia da U...,Infraestrutura,Instituição Financeira Nacional,Caixa Econômica Federal,Real,6.900000e+08,1,0,04/02/2016
101,5248,Estado,São Paulo,35,SP,None,Encaminhado à PGFN com manifestação técnica fa...,17944.000068/2013-64,2014-07-01T00:00:00Z,Operação contratual externa (com garantia da U...,Infraestrutura,Instituição Financeira Internacional,Corporação Andina de Fomento,Dólar dos EUA,2.000000e+08,1,0,07/08/2014
102,5701,Estado,São Paulo,35,SP,None,Encaminhado à PGFN com manifestação técnica fa...,17944.000175/2013-92,2013-06-13T00:00:00Z,Operação contratual externa (com garantia da U...,Multissetorial,Instituição Financeira Internacional,Banco Internacional para Reconstrução e Desenv...,Dólar dos EUA,3.000000e+08,1,0,03/07/2013

In [28]:
# 2) Quantas solicitações para o Estado podem ser consultadas para Minas Gerais
# com status em 'Arquivado por decurso de prazo' estão registradas?
df_mg = getPVLsFromAPI(uf="MG")
df_mg["status"].value_counts() # Arquivado por decurso de prazo = 1

status
Encaminhado à PGFN com manifestação técnica favorável    20
Deferido                                                  9
Arquivado a pedido                                        5
Arquivado pela STN                                        3
Arquivado                                                 3
Arquivado por decurso de prazo                            1
Indeferido                                                1
Name: count, dtype: int64

In [35]:
# 3) Qual é o município da Bahia com mais solicitações deferidas?
df_ba = getPVLsFromAPI(uf="BA", tipo_interessado="Município")

# Filtrar apenas os deferidos
deferidos = df_ba[df_ba["status"] == "Deferido"]

# Contar por município
contagem = deferidos.groupby("interessado").size()

# Município com maior quantidade
municipio_top = contagem.idxmax()
qtd_top = contagem.max()

print("Município da BA com mais deferidos:", municipio_top)
print("Quantidade:", qtd_top)

Município da BA com mais deferidos: Luís Eduardo Magalhães
Quantidade: 16

In [41]:
# 4) Salve um arquivo .csv com os dados de solicitações da Bahia, com interessado = 'Estado'
df_ba_estado = getPVLsFromAPI(uf="BA", tipo_interessado="Estado")
df_ba_estado.to_csv("BahiaEstado.csv", index=False)